all:
  hosts:
    <host-1>:
      ansible_host: <ip>
      ip: <ip>
      access_ip: <ip>
    worker-1:
      ansible_host: <ip>
      ip: <ip>
      access_ip: <ip>
  children:
    kube_control_plane:
      hosts:
        control-node-1:
    kube_node:
      hosts:
        worker-1:
    etcd:
      hosts:
        control-node-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
